# Generated by Django 4.1.13 on 2024-10-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0003_alter_analysis_balance_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='shareholders_pattern',
        ),
        migrations.CreateModel(
            name='shareholders_pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.JSONField(blank=True, null=True)),
                ('numbers', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analysis.company')),
            ],
        ),
    ]
