# Generated by Django 4.1.13 on 2024-10-27 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0005_analysis_director_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
