# Generated by Django 4.1.13 on 2024-10-28 00:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0006_analysis_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('company1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_company1', to='Analysis.company')),
                ('company2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_company2', to='Analysis.company')),
            ],
        ),
    ]
